### ISSUE TITLE
link-check modified files only variable based on event type

### ISSUE THREAD

**Issue by nicholaswilde** [nicholaswilde/recipes#1136]
Change link-check action to run all files based on schedule but only modified files when pushed normally.

```
name: Conditional Variable Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  set-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set variable based on event
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "EVENT_TYPE=push" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "EVENT_TYPE=pull_request" >> $GITHUB_ENV
          fi

  use-variable:
    runs-on: ubuntu-latest
    needs: set-variable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print event type
        run: echo "The event type is $EVENT_TYPE"
```
